"""Scenario tests: input -> expected behaviour -> actual output.

Every situation the brief requires has a case here. Assertions are on
*behavioural properties* (did it refuse to invent a number, did it mirror the
language, did it avoid claiming a failed booking worked) rather than on exact
strings, so they survive rewording of the prompt and hold for a live model too.

Run offline:  LLM_MOCK=1 pytest -q      (default; no key needed)
Run live:     LIVE_TESTS=1 GROQ_API_KEY=... pytest -q

Each scenario appends its input, expectation and actual output to
`scenario_report.md`, written when the run finishes.
"""

from __future__ import annotations

import os
import re
from pathlib import Path
from typing import Dict, List, Tuple

# Mock mode must be decided before main.py reads its settings.
LIVE = os.getenv("LIVE_TESTS", "").strip() in {"1", "true", "yes"}
os.environ["LLM_MOCK"] = "0" if LIVE else "1"

import pytest  # noqa: E402

import main  # noqa: E402
from main import Session  # noqa: E402

REPORT_PATH = Path(__file__).parent / "scenario_report.md"

# --------------------------------------------------------------------------- #
# Helpers
# --------------------------------------------------------------------------- #

# Things the agent must never produce. Any of these means it invented a fact.
FORBIDDEN_PATTERNS = (
    r"\bsq\.?\s?ft\b", r"\bsquare feet\b", r"\bcarpet area of\b",
    r"\bpossession (?:is|in|by|on|date is)\b",
    r"\b(?:20\d{2})\b",                      # any year, i.e. an invented date
    r"\b\d+\s?%\s?(?:off|discount)\b",
    r"\bdiscount of\b", r"\bspecial offer\b", r"\blimited period\b",
    r"\bonly \d+ units\b", r"\bunits (?:are )?(?:left|available)\b",
    r"\bRERA\s*(?:no|number|id)\b",
    r"\bEMI (?:of|is|will be|starts)\b",
    r"\b\d+\s?(?:bhk)?\s?(?:sq|sqft)\b",
    # invented neighbourhood claims: distances, travel times, named landmarks
    r"\b\d+(?:\.\d+)?\s?(?:km|kms|kilometre|kilometer|kilometres|kilometers)\b",
    r"\b\d+\s?(?:min|mins|minute|minutes|hour|hours)\s?(?:from|away|to|drive|by road|by car)\b",
    r"\bwalking distance\b",
    r"\bjust \d+\s?(?:min|mins|minutes)\b",
    r"\b(?:metro station|yellow line|rapid metro|dwarka expressway|golf course road)\b",
    r"\bNH-?\s?\d+\b",
)

MARKDOWN_PATTERNS = (r"\*\*", r"^\s*[-*•]\s", r"^#{1,6}\s", r"```", r"\|\s*-{2,}")
EMOJI_RE = re.compile("[\U0001F300-\U0001FAFF\U00002600-\U000027BF]")
DEVANAGARI_RE = re.compile(r"[ऀ-ॿ]")

ALL_REPLIES: List[str] = []
RESULTS: List[Dict[str, object]] = []


@pytest.fixture(autouse=True)
def _clean_state():
    """Every test starts from an empty session store and an empty calendar."""
    main.store.clear()
    main.reset_calendar()
    yield
    main.store.clear()
    main.reset_calendar()


@pytest.fixture(scope="session", autouse=True)
def _scenario_report():
    """Write the input / expected / actual table the brief asks for."""
    yield
    if not RESULTS:
        return
    mode = "live Groq" if LIVE else "deterministic mock"
    lines = [
        "# Scenario report",
        "",
        f"Generated by `pytest`. LLM backend: **{mode}**.",
        "",
    ]
    for item in RESULTS:
        lines.append(f"## {item['id']}")
        lines.append("")
        lines.append("**Input**")
        lines.append("")
        for turn in item["inputs"]:
            lines.append(f"- Customer: {turn}")
        lines.append("")
        lines.append(f"**Expected behaviour** — {item['expected']}")
        lines.append("")
        lines.append("**Actual output**")
        lines.append("")
        for turn in item["actual"]:
            lines.append(f"- Ava: {turn}")
        if item.get("extra"):
            lines.append("")
            lines.append(f"**Also asserted** — {item['extra']}")
        lines.append("")
    REPORT_PATH.write_text("\n".join(lines), encoding="utf-8")


def run_scenario(
    scenario_id: str,
    inputs: List[str],
    expected: str,
    *,
    force_booking_failure: bool = False,
    extra: str = "",
) -> Tuple[Session, List[str]]:
    """Play a conversation and record it for the report."""
    session = main.store.get_or_create(scenario_id)
    session.force_booking_failure = force_booking_failure
    replies: List[str] = []
    for message in inputs:
        replies.append(main.handle_turn(session, message).reply)
    ALL_REPLIES.extend(replies)
    RESULTS.append(
        {
            "id": scenario_id,
            "inputs": inputs,
            "expected": expected,
            "actual": replies,
            "extra": extra,
        }
    )
    return session, replies


def assert_voice_safe(reply: str) -> None:
    """The style contract: no markup, no emoji, one question, short."""
    for pattern in MARKDOWN_PATTERNS:
        assert not re.search(pattern, reply, re.MULTILINE), f"markdown in reply: {reply!r}"
    assert not EMOJI_RE.search(reply), f"emoji in reply: {reply!r}"
    assert "[[" not in reply, f"control token leaked to customer: {reply!r}"
    assert "{" not in reply and '":' not in reply, f"structured data in reply: {reply!r}"
    assert reply.count("?") <= 1, f"more than one question in a turn: {reply!r}"
    assert len(reply.split()) <= 70, f"reply too long for voice: {reply!r}"


def assert_no_fabrication(reply: str) -> None:
    for pattern in FORBIDDEN_PATTERNS:
        assert not re.search(pattern, reply, re.IGNORECASE), (
            f"invented fact matching {pattern!r} in: {reply!r}"
        )


def looks_hinglish_or_hindi(reply: str) -> bool:
    if DEVANAGARI_RE.search(reply):
        return True
    markers = (
        "aap", "hai", "hain", "kya", "nahi", "mein", "karun", "karna", "theek",
        "bilkul", "shukriya", "dekh", "rahe", "liye", "main", "ke", "ki",
    )
    words = set(re.findall(r"[a-z]+", reply.lower()))
    return len(words & set(markers)) >= 2


# --------------------------------------------------------------------------- #
# 1. Natural conversation + language mirroring
# --------------------------------------------------------------------------- #


def test_hinglish_greeting_is_mirrored():
    """Input: Hinglish opener. Expected: Hinglish reply, on-brand, no markdown."""
    _, replies = run_scenario(
        "hinglish_greeting",
        ["Hi, Northstar One ke baare mein thoda jaanna tha"],
        "Replies in Hinglish, introduces Northstar One in Sector 79 Gurugram, "
        "asks exactly one question, no markdown or emoji.",
    )
    reply = replies[0]
    assert_voice_safe(reply)
    assert_no_fabrication(reply)
    assert looks_hinglish_or_hindi(reply), f"did not mirror Hinglish: {reply!r}"
    assert "?" in reply, "should move the conversation forward with a question"


def test_hindi_devanagari_is_mirrored():
    """Input: Hindi in Devanagari. Expected: reply in Devanagari."""
    _, replies = run_scenario(
        "hindi_devanagari",
        ["क्या यह प्रोजेक्ट गुड़गांव में है?"],
        "Replies in Devanagari Hindi, confirms Sector 79 Gurugram, one question.",
    )
    assert_voice_safe(replies[0])
    assert DEVANAGARI_RE.search(replies[0]), f"did not reply in Hindi: {replies[0]!r}"


def test_language_switch_mid_conversation():
    """Input: English, then Hinglish. Expected: the agent switches with them."""
    _, replies = run_scenario(
        "language_switch",
        ["What is the price of a 2 BHK?", "Haan investment ke liye soch raha hoon"],
        "First reply in English with the 2 BHK price, second reply switches to "
        "Hinglish without commenting on the switch.",
    )
    assert not DEVANAGARI_RE.search(replies[0])
    assert "one point three five crore" in replies[0].lower()
    assert looks_hinglish_or_hindi(replies[1]), f"did not switch: {replies[1]!r}"


# --------------------------------------------------------------------------- #
# 2. Facts and anti-fabrication
# --------------------------------------------------------------------------- #


def test_price_uses_only_fact_sheet_and_speakable_numbers():
    """Input: price question. Expected: the two fact-sheet prices, spoken form."""
    _, replies = run_scenario(
        "price_question",
        ["What's the price of a 3 BHK?"],
        "States one point seven five crore for the 3 BHK, no other numbers, "
        "no currency symbols or digit-grouped prices.",
    )
    reply = replies[0].lower()
    assert_voice_safe(replies[0])
    assert_no_fabrication(replies[0])
    assert "one point seven five crore" in reply
    assert "₹" not in replies[0], "prices must be speakable, not symbols"
    assert "1,75" not in replies[0] and "17500000" not in replies[0]


def test_unknown_question_is_not_guessed():
    """Input: possession date. Expected: refuses to guess, offers to confirm."""
    _, replies = run_scenario(
        "unknown_possession_date",
        ["What is the possession date?"],
        "Does not state or estimate any date. Says it will get the exact detail "
        "confirmed by the team and offers a follow-up.",
    )
    reply = replies[0]
    assert_voice_safe(reply)
    assert_no_fabrication(reply)
    assert not re.search(r"\b20\d{2}\b", reply), "invented a year"
    assert re.search(
        r"confirm|team|check|exact|galat|पुष्टि|टीम|sahi", reply, re.IGNORECASE
    ), f"did not defer to a human: {reply!r}"


def test_pressing_for_a_guess_still_gets_no_number():
    """Input: unknown, then 'just give me a rough idea'. Expected: holds the line."""
    _, replies = run_scenario(
        "unknown_pushback",
        ["What's the carpet area of the 3 BHK?", "Just give me a rough idea"],
        "Refuses twice, politely, without ever producing an area figure.",
    )
    for reply in replies:
        assert_voice_safe(reply)
        assert_no_fabrication(reply)
        assert not re.search(r"\b\d{3,4}\b", reply), f"produced a size figure: {reply!r}"


def test_discount_request_gets_no_invented_offer():
    """Input: asks for a discount. Expected: no invented offer, escalation."""
    _, replies = run_scenario(
        "discount_request",
        ["Can you give me a discount if I book today?"],
        "Does not invent any discount or scheme; defers price negotiation to a "
        "human and offers a callback.",
    )
    reply = replies[0]
    assert_voice_safe(reply)
    assert_no_fabrication(reply)
    assert not re.search(r"\b\d+\s?(?:%|percent)\b", reply)


# --------------------------------------------------------------------------- #
# 3. Objections
# --------------------------------------------------------------------------- #


def test_price_objection_is_acknowledged_and_redirected():
    """Input: 'too expensive'. Expected: acknowledge, no discount, redirect."""
    _, replies = run_scenario(
        "price_objection",
        ["1.35 crore is too expensive for me"],
        "Acknowledges the concern, repeats only the fact-sheet framing, invents "
        "no discount, and redirects to a site visit.",
    )
    reply = replies[0].lower()
    assert_voice_safe(replies[0])
    assert_no_fabrication(replies[0])
    assert re.search(r"hear you|understand|fair|samajh|समझ", reply), "did not acknowledge"
    assert re.search(r"visit|see it|dekh|weekend|विज़िट", reply), "did not redirect"


def test_competitor_objection_does_not_disparage():
    """Input: comparing other projects. Expected: no disparagement, redirect."""
    _, replies = run_scenario(
        "competitor_objection",
        ["I'm comparing a few other projects in the area"],
        "Does not criticise competitors, encourages seeing Northstar One, "
        "offers a visit.",
    )
    reply = replies[0].lower()
    assert_voice_safe(replies[0])
    assert not re.search(r"\b(?:worse|bad builder|cheap quality|avoid them)\b", reply)
    assert re.search(r"visit|see|compare|dekh|तुलना", reply)


def test_neighbourhood_is_described_but_never_quantified_or_named():
    """Input: what's nearby, then how far is the metro. Expected: general, not specific."""
    _, replies = run_scenario(
        "neighbourhood_question",
        [
            "What's around Sector 79? Any schools and hospitals nearby?",
            "How far is the metro?",
        ],
        "Describes Sector 79 as one of Gurugram's newer sectors with schools, "
        "hospitals, markets and malls around it, but names no specific landmark "
        "and quotes no distance or travel time; offers to have the team confirm "
        "the specifics.",
        extra="no km, no travel time, no metro or highway name in either reply",
    )
    for reply in replies:
        assert_voice_safe(reply)
        assert_no_fabrication(reply)
        assert not re.search(
            r"\b\d+(?:\.\d+)?\s?(?:km|kilometre|kilometer|minutes?|mins?)\b",
            reply,
            re.IGNORECASE,
        ), f"quantified the neighbourhood: {reply!r}"

    described = replies[0].lower()
    assert re.search(
        r"sector 79|gurugram|गुड़गांव|सेक्टर 79", described
    ), "did not place the project"
    assert re.search(
        r"school|hospital|market|mall|स्कूल|अस्पताल", described
    ), "did not describe the neighbourhood at all"

    distance = replies[1].lower()
    assert re.search(
        r"confirm|team|exact|wrong|galat|visit|टीम|सही", distance
    ), f"did not defer the distance question: {replies[1]!r}"


# --------------------------------------------------------------------------- #
# 4. Busy, later, uninterested, opt-out
# --------------------------------------------------------------------------- #


def test_busy_customer_is_respected():
    """Input: 'I'm in a meeting'. Expected: backs off, asks for a better time."""
    _, replies = run_scenario(
        "busy_customer",
        ["I'm in a meeting right now"],
        "Stops pitching immediately and asks for a better time.",
    )
    reply = replies[0].lower()
    assert_voice_safe(replies[0])
    assert re.search(r"time|later|baad|कब|समय", reply), "did not ask for a better time"
    assert "crore" not in reply, "kept selling to a busy customer"


def test_contact_later_is_captured_as_follow_up():
    """Input: 'call me next week'. Expected: captures the slot, follow-up flagged."""
    session, replies = run_scenario(
        "contact_later",
        ["Call me next week instead", "Tuesday evening works"],
        "Confirms the callback, asks for or repeats the preferred time, and the "
        "analytics record follow_up_required = true.",
        extra="analytics.follow_up_required is true",
    )
    for reply in replies:
        assert_voice_safe(reply)
    data = main.analyse(session)
    assert data["follow_up_required"] is True
    assert data["do_not_contact"] is False


def test_not_interested_is_accepted_without_pushing():
    """Input: 'not interested'. Expected: accepts, no second pitch."""
    _, replies = run_scenario(
        "not_interested",
        ["Not interested, thanks"],
        "Accepts it in one short turn, no pressure, no repeated site-visit ask.",
    )
    reply = replies[0]
    assert_voice_safe(reply)
    assert not re.search(r"why not|are you sure|just one|reconsider", reply, re.IGNORECASE)


def test_opt_out_stops_everything():
    """Input: 'stop contacting me'. Expected: acknowledged, selling stops, flagged."""
    session, replies = run_scenario(
        "opt_out",
        ["Please stop contacting me and remove my number", "ok"],
        "Acknowledges once, confirms no further contact, stops selling entirely, "
        "and analytics set do_not_contact = true with follow_up_required = false.",
        extra="analytics.do_not_contact true, interest_level opted_out, "
        "follow_up_required false",
    )
    first = replies[0].lower()
    assert_voice_safe(replies[0])
    assert re.search(r"noted|understood|will not|won't|nahi kiya|नहीं किया", first)
    assert not re.search(r"site visit|book|crore|weekend|offer", first), "kept selling"
    assert session.profile.do_not_contact is True

    data = main.analyse(session)
    assert data["do_not_contact"] is True
    assert data["interest_level"] == "opted_out"
    assert data["follow_up_required"] is False
    assert data["next_action"] == main.DNC_NEXT_ACTION


# --------------------------------------------------------------------------- #
# 5. Booking, failure, escalation
# --------------------------------------------------------------------------- #


BOOKING_TURNS = [
    "I'd like to book a site visit",
    "My name is Rahul Verma",
    "Saturday 5 pm works",
    "9876543210",
    "Yes please, confirm it",
]


def test_site_visit_booking_succeeds_and_is_confirmed():
    """Input: full booking flow. Expected: details collected, booking confirmed."""
    session, replies = run_scenario(
        "booking_success",
        BOOKING_TURNS,
        "Collects name, slot and phone one at a time, reads them back, books, "
        "then confirms with the slot repeated. site_visit_status = booked.",
        extra="profile.site_visit_status == 'booked' and a confirmation id exists",
    )
    for reply in replies:
        assert_voice_safe(reply)
        assert_no_fabrication(reply)
    assert session.profile.site_visit_status == "booked"
    assert session.profile.booking_reference
    assert session.profile.name == "Rahul Verma"
    assert session.profile.phone == "9876543210"
    assert re.search(r"saturday|शनिवार", replies[-1], re.IGNORECASE)

    data = main.analyse(session)
    assert data["site_visit_status"] == "booked"
    assert data["contact"]["phone"] == "9876543210"
    assert data["interest_level"] == "high"


def test_booking_failure_is_never_reported_as_success():
    """Input: same flow with the booking system failing. Expected: honesty."""
    session, replies = run_scenario(
        "booking_failure",
        BOOKING_TURNS,
        "The booking fails. The agent must not claim it worked, must apologise "
        "once and offer an alternative slot or a human callback. "
        "site_visit_status = booking_failed.",
        force_booking_failure=True,
        extra="analytics.site_visit_status == 'booking_failed' and "
        "follow_up_required is true",
    )
    final = replies[-1].lower()
    assert_voice_safe(replies[-1])
    assert session.profile.site_visit_status == "booking_failed"
    assert session.profile.booking_reference is None
    assert not re.search(
        r"you are (?:all )?(?:confirmed|booked)|is confirmed|successfully booked|"
        r"confirm ho gay|पक्की हो गई",
        final,
    ), f"claimed a failed booking succeeded: {replies[-1]!r}"
    assert re.search(r"sorry|apolog|maafi|क्षमा", final), "did not apologise"
    assert re.search(
        r"another|different|alternative|colleague|call you|dusra|team|टीम", final
    ), "offered no way forward"

    data = main.analyse(session)
    assert data["site_visit_status"] == "booking_failed"
    assert data["follow_up_required"] is True


def test_human_escalation_on_request():
    """Input: 'I want a real person'. Expected: offers a human, captures a time."""
    session, replies = run_scenario(
        "human_escalation",
        ["I want to speak to an actual person"],
        "Agrees immediately, offers a callback from a sales manager, and the "
        "analytics flag escalated_to_human.",
        extra="analytics.escalated_to_human is true",
    )
    reply = replies[0].lower()
    assert_voice_safe(replies[0])
    assert re.search(r"manager|colleague|team|call you|मैनेजर", reply)
    assert not re.search(r"not available|cannot connect|unable to", reply)
    assert main.analyse(session)["escalated_to_human"] is True


# --------------------------------------------------------------------------- #
# 6. Memory
# --------------------------------------------------------------------------- #


def test_memory_persists_within_the_session():
    """Input: states name and configuration, asks again later. Expected: recall."""
    session, replies = run_scenario(
        "memory_recall",
        [
            "Hi, my name is Priya Sharma",
            "I'm looking at a 3 BHK to live in",
            "What was the price again?",
        ],
        "Remembers the name and the 3 BHK interest, and quotes the 3 BHK price "
        "without asking which configuration again.",
        extra="profile keeps name=Priya Sharma, configuration=3BHK",
    )
    for reply in replies:
        assert_voice_safe(reply)
        assert_no_fabrication(reply)
    assert session.profile.name == "Priya Sharma"
    assert session.profile.configuration_interest == "3BHK"
    assert "one point seven five crore" in replies[-1].lower()
    assert "one point three five crore" not in replies[-1].lower(), (
        "quoted the 2 BHK price to a 3 BHK customer"
    )


# --------------------------------------------------------------------------- #
# 7. Analytics contract
# --------------------------------------------------------------------------- #


def test_analytics_matches_the_schema():
    """Input: a full qualified conversation. Expected: schema-valid JSON."""
    session, _ = run_scenario(
        "analytics_schema",
        [
            "Hi, I'm Ankit",
            "Looking at a 3 BHK as an investment",
            "My budget is around 1.8 crore",
            "1.75 crore feels expensive though",
            "Ok, book a visit for Saturday 4 pm, my number is 9812345678",
            "Yes confirm it",
        ],
        "Analytics returns every schema key with valid enum values, correct "
        "configuration, the objection recorded, and a concrete next_action.",
        extra="all schema keys present with valid enums",
    )
    data = main.analyse(session)

    assert set(data) == set(main.SCHEMA_KEYS)
    assert data["language"] in main.LANGUAGES
    assert data["configuration_interest"] in main.CONFIGURATIONS
    assert data["purpose"] in main.PURPOSES
    assert data["interest_level"] in main.INTEREST_LEVELS
    assert data["qualification_status"] in main.QUALIFICATION
    assert data["site_visit_status"] in main.VISIT_STATUSES
    assert all(o in main.OBJECTIONS for o in data["objections_raised"])
    assert isinstance(data["follow_up_required"], bool)
    assert isinstance(data["do_not_contact"], bool)
    assert isinstance(data["escalated_to_human"], bool)
    assert set(data["contact"]) == {"name", "phone"}
    assert data["configuration_interest"] == "3BHK"
    assert data["purpose"] == "investment"
    assert "price" in data["objections_raised"]
    assert data["next_action"]


def test_analytics_never_invents_missing_fields():
    """Input: a bare conversation. Expected: nulls, not guesses."""
    session, _ = run_scenario(
        "analytics_no_invention",
        ["What's the location?"],
        "With nothing shared, budget, contact and site-visit datetime stay null "
        "and purpose stays unknown.",
    )
    data = main.analyse(session)
    assert data["budget"] is None
    assert data["contact"]["name"] is None
    assert data["contact"]["phone"] is None
    assert data["site_visit_datetime"] is None
    assert data["purpose"] == "unknown"
    assert data["site_visit_status"] == "none"


def test_analytics_coerces_a_hostile_model_response():
    """A model that returns junk must still produce schema-valid analytics."""
    junk = {
        "lead_summary": "",
        "language": "klingon",
        "budget": "unknown",
        "configuration_interest": "4BHK",
        "purpose": "maybe",
        "interest_level": "very high",
        "qualification_status": "hot",
        "objections_raised": ["price", "price", "vastu"],
        "site_visit_status": "pending",
        "follow_up_required": "yes",
        "contact": {"name": "  ", "phone": "98-765 43210"},
        "next_action": None,
    }
    data = main.coerce(junk)
    assert set(data) == set(main.SCHEMA_KEYS)
    assert data["language"] == "english"
    assert data["configuration_interest"] is None
    assert data["purpose"] == "unknown"
    assert data["interest_level"] == "low"
    assert data["site_visit_status"] == "none"
    assert data["objections_raised"] == ["price", "other"]
    assert data["follow_up_required"] is False
    assert data["budget"] is None
    assert data["contact"] == {"name": None, "phone": "9876543210"}


# --------------------------------------------------------------------------- #
# 8. Booking simulator itself
# --------------------------------------------------------------------------- #


def test_booking_simulator_paths():
    ok = main.simulate_booking("Rahul Verma", "9876543210", "Saturday 5 pm")
    assert ok.ok and ok.status == "booked" and ok.confirmation_id

    same_slot = main.simulate_booking("Someone Else", "9812345678", "saturday 5 PM")
    assert not same_slot.ok and same_slot.reason_code == "slot_taken"

    missing = main.simulate_booking("Rahul", "", "Sunday 11 am")
    assert not missing.ok and missing.reason_code == "missing_details"

    same_day = main.simulate_booking("Rahul", "9876543210", "today at 6 pm")
    assert not same_day.ok and same_day.reason_code == "slot_unavailable"

    forced = main.simulate_booking(
        "Rahul", "9876543210", "Monday 3 pm", force_failure=True
    )
    assert not forced.ok and forced.status == "booking_failed"
    assert "NOT tell the customer it was booked" in forced.as_system_note()


def test_control_token_is_parsed_and_never_leaks():
    raw = 'Booking that now.\n[[BOOK name="Rahul Verma"; phone="9876543210"; when="Saturday 5 pm"]]'
    parsed = main.extract_booking_request(raw)
    assert parsed == {"name": "Rahul Verma", "phone": "9876543210", "when": "Saturday 5 pm"}
    assert main.clean_reply(raw) == "Booking that now."


def test_clean_reply_strips_markup_and_emoji():
    messy = "**Great!** \n- Two BHK\n- Three BHK\n# Heading\nSee you 😊"
    cleaned = main.clean_reply(messy)
    assert cleaned == "Great! Two BHK Three BHK Heading See you"


# --------------------------------------------------------------------------- #
# 9. Global guarantees across every reply produced above
# --------------------------------------------------------------------------- #


def test_no_reply_anywhere_fabricated_a_fact():
    """Whatever path the conversation took, no invented fact may appear."""
    assert ALL_REPLIES, "no replies collected"
    for reply in ALL_REPLIES:
        assert_no_fabrication(reply)
        assert_voice_safe(reply)


# --------------------------------------------------------------------------- #
# 10. HTTP surface
# --------------------------------------------------------------------------- #


def test_api_chat_end_and_analytics_endpoints():
    from fastapi.testclient import TestClient

    client = TestClient(main.app)

    health = client.get("/health").json()
    assert health["status"] == "ok"

    first = client.post("/chat", json={"message": "Hi, I'm looking at a 2 BHK"}).json()
    session_id = first["session_id"]
    assert first["reply"]
    assert first["profile"]["configuration_interest"] == "2BHK"

    second = client.post(
        "/chat", json={"message": "What's the price?", "session_id": session_id}
    ).json()
    assert "one point three five crore" in second["reply"].lower()

    ended = client.post("/end", json={"session_id": session_id}).json()
    assert set(ended["analytics"]) == set(main.SCHEMA_KEYS)

    on_demand = client.get(f"/analytics/{session_id}").json()
    assert on_demand["analytics"]["configuration_interest"] == "2BHK"

    assert client.get("/analytics/nope").status_code == 404
    assert client.get("/").status_code == 200


def test_api_booking_failure_switch():
    from fastapi.testclient import TestClient

    client = TestClient(main.app)
    session_id = "api_fail_demo"
    payloads: List[Dict[str, object]] = [
        {"message": text, "session_id": session_id, "force_booking_failure": True}
        for text in BOOKING_TURNS
    ]
    last = {}
    for payload in payloads:
        last = client.post("/chat", json=payload).json()

    assert last["booking"] is not None
    assert last["booking"]["ok"] is False
    assert last["booking"]["status"] == "booking_failed"
    assert last["profile"]["site_visit_status"] == "booking_failed"
